name = "Developers Dungeon SMP"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "001e9aaf220d18b0d2ad118e4aa5bf1e2d1a9b456889432e9469510203e7d38c"

[versions]
fabric = "0.16.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
